#!/bin/bash
#ddev-generated

# =============================================================================
# Ralph DDEV Entrypoint
# =============================================================================

# --- Set up SSH client (keys generated by ddev-ai-ssh add-on) ---
SSH_KEY_DIR="/var/www/html/.ddev/.agent-ssh-keys"
mkdir -p ~/.ssh && chmod 700 ~/.ssh
cp "$SSH_KEY_DIR/id_ed25519" ~/.ssh/ddev_agent_key 2>/dev/null
chmod 600 ~/.ssh/ddev_agent_key 2>/dev/null

exec "$@"
